In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
import sklearn as sklearn

In [4]:
df=pd.read_csv("data.csv")
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [5]:
num_rows, num_columns = df.shape

print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

Number of rows: 569
Number of columns: 33

In [6]:
missing_values_per_row = df.isnull().sum(axis=1)
print(missing_values_per_row)

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    1
Length: 569, dtype: int64

In [7]:
import pandas as pd

# Assuming 'data' is your DataFrame
for index, row in df.iterrows():
    null_columns = row.index[row.isnull()]
    if len(null_columns) > 0:
        print(f"Row {index}: Null values in columns - {', '.join(null_columns)}")

Row 0: Null values in columns - Unnamed: 32
Row 1: Null values in columns - Unnamed: 32
Row 2: Null values in columns - Unnamed: 32
Row 3: Null values in columns - Unnamed: 32
Row 4: Null values in columns - Unnamed: 32
Row 5: Null values in columns - Unnamed: 32
Row 6: Null values in columns - Unnamed: 32
Row 7: Null values in columns - Unnamed: 32
Row 8: Null values in columns - Unnamed: 32
Row 9: Null values in columns - Unnamed: 32
Row 10: Null values in columns - Unnamed: 32
Row 11: Null values in columns - Unnamed: 32
Row 12: Null values in columns - Unnamed: 32
Row 13: Null values in columns - Unnamed: 32
Row 14: Null values in columns - Unnamed: 32
Row 15: Null values in columns - Unnamed: 32
Row 16: Null values in columns - Unnamed: 32
Row 17: Null values in columns - Unnamed: 32
Row 18: Null values in columns - Unnamed: 32
Row 19: Null values in columns - Unnamed: 32
Row 20: Null values in columns - Unnamed: 32
Row 21: Null values in columns - Unnamed: 32
Row 22: Null values in columns - Unnamed: 32
Row 23: Null values in columns - Unnamed: 32
Row 24: Null values in columns - Unnamed: 32
Row 25: Null values in columns - Unnamed: 32
Row 26: Null values in columns - Unnamed: 32
Row 27: Null values in columns - Unnamed: 32
Row 28: Null values in columns - Unnamed: 32
Row 29: Null values in columns - Unnamed: 32
Row 30: Null values in columns - Unnamed: 32
Row 31: Null values in columns - Unnamed: 32
Row 32: Null values in columns - Unnamed: 32
Row 33: Null values in columns - Unnamed: 32
Row 34: Null values in columns - Unnamed: 32
Row 35: Null values in columns - Unnamed: 32
Row 36: Null values in columns - Unnamed: 32
Row 37: Null values in columns - Unnamed: 32
Row 38: Null values in columns - Unnamed: 32
Row 39: Null values in columns - Unnamed: 32
Row 40: Null values in columns - Unnamed: 32
Row 41: Null values in columns - Unnamed: 32
Row 42: Null values in columns - Unnamed: 32
Row 43: Null values in columns - Unnamed: 32
Row 44: Null values in columns - Unnamed: 32
Row 45: Null values in columns - Unnamed: 32
Row 46: Null values in columns - Unnamed: 32
Row 47: Null values in columns - Unnamed: 32
Row 48: Null values in columns - Unnamed: 32
Row 49: Null values in columns - Unnamed: 32
Row 50: Null values in columns - Unnamed: 32
Row 51: Null values in columns - Unnamed: 32
Row 52: Null values in columns - Unnamed: 32
Row 53: Null values in columns - Unnamed: 32
Row 54: Null values in columns - Unnamed: 32
Row 55: Null values in columns - Unnamed: 32
Row 56: Null values in columns - Unnamed: 32
Row 57: Null values in columns - Unnamed: 32
Row 58: Null values in columns - Unnamed: 32
Row 59: Null values in columns - Unnamed: 32
Row 60: Null values in columns - Unnamed: 32
Row 61: Null values in columns - Unnamed: 32
Row 62: Null values in columns - Unnamed: 32
Row 63: Null values in columns - Unnamed: 32
Row 64: Null values in columns - Unnamed: 32
Row 65: Null values in columns - Unnamed: 32
Row 66: Null values in columns - Unnamed: 32
Row 67: Null values in columns - Unnamed: 32
Row 68: Null values in columns - Unnamed: 32
Row 69: Null values in columns - Unnamed: 32
Row 70: Null values in columns - Unnamed: 32
Row 71: Null values in columns - Unnamed: 32
Row 72: Null values in columns - Unnamed: 32
Row 73: Null values in columns - Unnamed: 32
Row 74: Null values in columns - Unnamed: 32
Row 75: Null values in columns - Unnamed: 32
Row 76: Null values in columns - Unnamed: 32
Row 77: Null values in columns - Unnamed: 32
Row 78: Null values in columns - Unnamed: 32
Row 79: Null values in columns - Unnamed: 32
Row 80: Null values in columns - Unnamed: 32
Row 81: Null values in columns - Unnamed: 32
Row 82: Null values in columns - Unnamed: 32
Row 83: Null values in columns - Unnamed: 32
Row 84: Null values in columns - Unnamed: 32
Row 85: Null values in columns - Unnamed: 32
Row 86: Null values in columns - Unnamed: 32
Row 87: Null values in columns - Unnamed: 32
Row 88: Null values in columns - Unnamed: 32
Row 89: Null values in columns - Unnamed: 32
Row 90: Null values in columns - Unnamed: 32
Row 91: Null values in columns - Unnamed: 32
Row 92: Null values in columns - Unnamed: 32
Row 93: Null values in columns - Unnamed: 32
Row 94: Null values in columns - Unnamed: 32
Row 95: Null values in columns - Unnamed: 32
Row 96: Null values in columns - Unnamed: 32
Row 97: Null values in columns - Unnamed: 32
Row 98: Null values in columns - Unnamed: 32
Row 99: Null values in columns - Unnamed: 32
Row 100: Null values in columns - Unnamed: 32
Row 101: Null values in columns - Unnamed: 32
Row 102: Null values in columns - Unnamed: 32
Row 103: Null values in columns - Unnamed: 32
Row 104: Null values in columns - Unnamed: 32
Row 105: Null values in columns - Unnamed: 32
Row 106: Null values in columns - Unnamed: 32
Row 107: Null values in columns - Unnamed: 32
Row 108: Null values in columns - Unnamed: 32
Row 109: Null values in columns - Unnamed: 32
Row 110: Null values in columns - Unnamed: 32
Row 111: Null values in columns - Unnamed: 32
Row 112: Null values in columns - Unnamed: 32
Row 113: Null values in columns - Unnamed: 32
Row 114: Null values in columns - Unnamed: 32
Row 115: Null values in columns - Unnamed: 32
Row 116: Null values in columns - Unnamed: 32
Row 117: Null values in columns - Unnamed: 32
Row 118: Null values in columns - Unnamed: 32
Row 119: Null values in columns - Unnamed: 32
Row 120: Null values in columns - Unnamed: 32
Row 121: Null values in columns - Unnamed: 32
Row 122: Null values in columns - Unnamed: 32
Row 123: Null values in columns - Unnamed: 32
Row 124: Null values in columns - Unnamed: 32
Row 125: Null values in columns - Unnamed: 32
Row 126: Null values in columns - Unnamed: 32
Row 127: Null values in columns - Unnamed: 32
Row 128: Null values in columns - Unnamed: 32
Row 129: Null values in columns - Unnamed: 32
Row 130: Null values in columns - Unnamed: 32
Row 131: Null values in columns - Unnamed: 32
Row 132: Null values in columns - Unnamed: 32
Row 133: Null values in columns - Unnamed: 32
Row 134: Null values in columns - Unnamed: 32
Row 135: Null values in columns - Unnamed: 32
Row 136: Null values in columns - Unnamed: 32
Row 137: Null values in columns - Unnamed: 32
Row 138: Null values in columns - Unnamed: 32
Row 139: Null values in columns - Unnamed: 32
Row 140: Null values in columns - Unnamed: 32
Row 141: Null values in columns - Unnamed: 32
Row 142: Null values in columns - Unnamed: 32
Row 143: Null values in columns - Unnamed: 32
Row 144: Null values in columns - Unnamed: 32
Row 145: Null values in columns - Unnamed: 32
Row 146: Null values in columns - Unnamed: 32
Row 147: Null values in columns - Unnamed: 32
Row 148: Null values in columns - Unnamed: 32
Row 149: Null values in columns - Unnamed: 32
Row 150: Null values in columns - Unnamed: 32
Row 151: Null values in columns - Unnamed: 32
Row 152: Null values in columns - Unnamed: 32
Row 153: Null values in columns - Unnamed: 32
Row 154: Null values in columns - Unnamed: 32
Row 155: Null values in columns - Unnamed: 32
Row 156: Null values in columns - Unnamed: 32
Row 157: Null values in columns - Unnamed: 32
Row 158: Null values in columns - Unnamed: 32
Row 159: Null values in columns - Unnamed: 32
Row 160: Null values in columns - Unnamed: 32
Row 161: Null values in columns - Unnamed: 32
Row 162: Null values in columns - Unnamed: 32
Row 163: Null values in columns - Unnamed: 32
Row 164: Null values in columns - Unnamed: 32
Row 165: Null values in columns - Unnamed: 32
Row 166: Null values in columns - Unnamed: 32
Row 167: Null values in columns - Unnamed: 32
Row 168: Null values in columns - Unnamed: 32
Row 169: Null values in columns - Unnamed: 32
Row 170: Null values in columns - Unnamed: 32
Row 171: Null values in columns - Unnamed: 32
Row 172: Null values in columns - Unnamed: 32
Row 173: Null values in columns - Unnamed: 32
Row 174: Null values in columns - Unnamed: 32
Row 175: Null values in columns - Unnamed: 32
Row 176: Null values in columns - Unnamed: 32
Row 177: Null values in columns - Unnamed: 32
Row 178: Null values in columns - Unnamed: 32
Row 179: Null values in columns - Unnamed: 32
Row 180: Null values in columns - Unnamed: 32
Row 181: Null values in columns - Unnamed: 32
Row 182: Null values in columns - Unnamed: 32
Row 183: Null values in columns - Unnamed: 32
Row 184: Null values in columns - Unnamed: 32
Row 185: Null values in columns - Unnamed: 32
Row 186: Null values in columns - Unnamed: 32
Row 187: Null values in columns - Unnamed: 32
Row 188: Null values in columns - Unnamed: 32
Row 189: Null values in columns - Unnamed: 32
Row 190: Null values in columns - Unnamed: 32
Row 191: Null values in columns - Unnamed: 32
Row 192: Null values in columns - Unnamed: 32
Row 193: Null values in columns - Unnamed: 32
Row 194: Null values in columns - Unnamed: 32
Row 195: Null values in columns - Unnamed: 32
Row 196: Null values in columns - Unnamed: 32
Row 197: Null values in columns - Unnamed: 32
Row 198: Null values in columns - Unnamed: 32
Row 199: Null values in columns - Unnamed: 32
Row 200: Null values in columns - Unnamed: 32
Row 201: Null values in columns - Unnamed: 32
Row 202: Null values in columns - Unnamed: 32
Row 203: Null values in columns - Unnamed: 32
Row 204: Null values in columns - Unnamed: 32
Row 205: Null values in columns - Unnamed: 32
Row 206: Null values in columns - Unnamed: 32
Row 207: Null values in columns - Unnamed: 32
Row 208: Null values in columns - Unnamed: 32
Row 209: Null values in columns - Unnamed: 32
Row 210: Null values in columns - Unnamed: 32
Row 211: Null values in columns - Unnamed: 32
Row 212: Null values in columns - Unnamed: 32
Row 213: Null values in columns - Unnamed: 32
Row 214: Null values in columns - Unnamed: 32
Row 215: Null values in columns - Unnamed: 32
Row 216: Null values in columns - Unnamed: 32
Row 217: Null values in columns - Unnamed: 32
Row 218: Null values in columns - Unnamed: 32
Row 219: Null values in columns - Unnamed: 32
Row 220: Null values in columns - Unnamed: 32
Row 221: Null values in columns - Unnamed: 32
Row 222: Null values in columns - Unnamed: 32
Row 223: Null values in columns - Unnamed: 32
Row 224: Null values in columns - Unnamed: 32
Row 225: Null values in columns - Unnamed: 32
Row 226: Null values in columns - Unnamed: 32
Row 227: Null values in columns - Unnamed: 32
Row 228: Null values in columns - Unnamed: 32
Row 229: Null values in columns - Unnamed: 32
Row 230: Null values in columns - Unnamed: 32
Row 231: Null values in columns - Unnamed: 32
Row 232: Null values in columns - Unnamed: 32
Row 233: Null values in columns - Unnamed: 32
Row 234: Null values in columns - Unnamed: 32
Row 235: Null values in columns - Unnamed: 32
Row 236: Null values in columns - Unnamed: 32
Row 237: Null values in columns - Unnamed: 32
Row 238: Null values in columns - Unnamed: 32
Row 239: Null values in columns - Unnamed: 32
Row 240: Null values in columns - Unnamed: 32
Row 241: Null values in columns - Unnamed: 32
Row 242: Null values in columns - Unnamed: 32
Row 243: Null values in columns - Unnamed: 32
Row 244: Null values in columns - Unnamed: 32
Row 245: Null values in columns - Unnamed: 32
Row 246: Null values in columns - Unnamed: 32
Row 247: Null values in columns - Unnamed: 32
Row 248: Null values in columns - Unnamed: 32
Row 249: Null values in columns - Unnamed: 32
Row 250: Null values in columns - Unnamed: 32
Row 251: Null values in columns - Unnamed: 32
Row 252: Null values in columns - Unnamed: 32
Row 253: Null values in columns - Unnamed: 32
Row 254: Null values in columns - Unnamed: 32
Row 255: Null values in columns - Unnamed: 32
Row 256: Null values in columns - Unnamed: 32
Row 257: Null values in columns - Unnamed: 32
Row 258: Null values in columns - Unnamed: 32
Row 259: Null values in columns - Unnamed: 32
Row 260: Null values in columns - Unnamed: 32
Row 261: Null values in columns - Unnamed: 32
Row 262: Null values in columns - Unnamed: 32
Row 263: Null values in columns - Unnamed: 32
Row 264: Null values in columns - Unnamed: 32
Row 265: Null values in columns - Unnamed: 32
Row 266: Null values in columns - Unnamed: 32
Row 267: Null values in columns - Unnamed: 32
Row 268: Null values in columns - Unnamed: 32
Row 269: Null values in columns - Unnamed: 32
Row 270: Null values in columns - Unnamed: 32
Row 271: Null values in columns - Unnamed: 32
Row 272: Null values in columns - Unnamed: 32
Row 273: Null values in columns - Unnamed: 32
Row 274: Null values in columns - Unnamed: 32
Row 275: Null values in columns - Unnamed: 32
Row 276: Null values in columns - Unnamed: 32
Row 277: Null values in columns - Unnamed: 32
Row 278: Null values in columns - Unnamed: 32
Row 279: Null values in columns - Unnamed: 32
Row 280: Null values in columns - Unnamed: 32
Row 281: Null values in columns - Unnamed: 32
Row 282: Null values in columns - Unnamed: 32
Row 283: Null values in columns - Unnamed: 32
Row 284: Null values in columns - Unnamed: 32
Row 285: Null values in columns - Unnamed: 32
Row 286: Null values in columns - Unnamed: 32
Row 287: Null values in columns - Unnamed: 32
Row 288: Null values in columns - Unnamed: 32
Row 289: Null values in columns - Unnamed: 32
Row 290: Null values in columns - Unnamed: 32
Row 291: Null values in columns - Unnamed: 32
Row 292: Null values in columns - Unnamed: 32
Row 293: Null values in columns - Unnamed: 32
Row 294: Null values in columns - Unnamed: 32
Row 295: Null values in columns - Unnamed: 32
Row 296: Null values in columns - Unnamed: 32
Row 297: Null values in columns - Unnamed: 32
Row 298: Null values in columns - Unnamed: 32
Row 299: Null values in columns - Unnamed: 32
Row 300: Null values in columns - Unnamed: 32
Row 301: Null values in columns - Unnamed: 32
Row 302: Null values in columns - Unnamed: 32
Row 303: Null values in columns - Unnamed: 32
Row 304: Null values in columns - Unnamed: 32
Row 305: Null values in columns - Unnamed: 32
Row 306: Null values in columns - Unnamed: 32
Row 307: Null values in columns - Unnamed: 32
Row 308: Null values in columns - Unnamed: 32
Row 309: Null values in columns - Unnamed: 32
Row 310: Null values in columns - Unnamed: 32
Row 311: Null values in columns - Unnamed: 32
Row 312: Null values in columns - Unnamed: 32
Row 313: Null values in columns - Unnamed: 32
Row 314: Null values in columns - Unnamed: 32
Row 315: Null values in columns - Unnamed: 32
Row 316: Null values in columns - Unnamed: 32
Row 317: Null values in columns - Unnamed: 32
Row 318: Null values in columns - Unnamed: 32
Row 319: Null values in columns - Unnamed: 32
Row 320: Null values in columns - Unnamed: 32
Row 321: Null values in columns - Unnamed: 32
Row 322: Null values in columns - Unnamed: 32
Row 323: Null values in columns - Unnamed: 32
Row 324: Null values in columns - Unnamed: 32
Row 325: Null values in columns - Unnamed: 32
Row 326: Null values in columns - Unnamed: 32
Row 327: Null values in columns - Unnamed: 32
Row 328: Null values in columns - Unnamed: 32
Row 329: Null values in columns - Unnamed: 32
Row 330: Null values in columns - Unnamed: 32
Row 331: Null values in columns - Unnamed: 32
Row 332: Null values in columns - Unnamed: 32
Row 333: Null values in columns - Unnamed: 32
Row 334: Null values in columns - Unnamed: 32
Row 335: Null values in columns - Unnamed: 32
Row 336: Null values in columns - Unnamed: 32
Row 337: Null values in columns - Unnamed: 32
Row 338: Null values in columns - Unnamed: 32
Row 339: Null values in columns - Unnamed: 32
Row 340: Null values in columns - Unnamed: 32
Row 341: Null values in columns - Unnamed: 32
Row 342: Null values in columns - Unnamed: 32
Row 343: Null values in columns - Unnamed: 32
Row 344: Null values in columns - Unnamed: 32
Row 345: Null values in columns - Unnamed: 32
Row 346: Null values in columns - Unnamed: 32
Row 347: Null values in columns - Unnamed: 32
Row 348: Null values in columns - Unnamed: 32
Row 349: Null values in columns - Unnamed: 32
Row 350: Null values in columns - Unnamed: 32
Row 351: Null values in columns - Unnamed: 32
Row 352: Null values in columns - Unnamed: 32
Row 353: Null values in columns - Unnamed: 32
Row 354: Null values in columns - Unnamed: 32
Row 355: Null values in columns - Unnamed: 32
Row 356: Null values in columns - Unnamed: 32
Row 357: Null values in columns - Unnamed: 32
Row 358: Null values in columns - Unnamed: 32
Row 359: Null values in columns - Unnamed: 32
Row 360: Null values in columns - Unnamed: 32
Row 361: Null values in columns - Unnamed: 32
Row 362: Null values in columns - Unnamed: 32
Row 363: Null values in columns - Unnamed: 32
Row 364: Null values in columns - Unnamed: 32
Row 365: Null values in columns - Unnamed: 32
Row 366: Null values in columns - Unnamed: 32
Row 367: Null values in columns - Unnamed: 32
Row 368: Null values in columns - Unnamed: 32
Row 369: Null values in columns - Unnamed: 32
Row 370: Null values in columns - Unnamed: 32
Row 371: Null values in columns - Unnamed: 32
Row 372: Null values in columns - Unnamed: 32
Row 373: Null values in columns - Unnamed: 32
Row 374: Null values in columns - Unnamed: 32
Row 375: Null values in columns - Unnamed: 32
Row 376: Null values in columns - Unnamed: 32
Row 377: Null values in columns - Unnamed: 32
Row 378: Null values in columns - Unnamed: 32
Row 379: Null values in columns - Unnamed: 32
Row 380: Null values in columns - Unnamed: 32
Row 381: Null values in columns - Unnamed: 32
Row 382: Null values in columns - Unnamed: 32
Row 383: Null values in columns - Unnamed: 32
Row 384: Null values in columns - Unnamed: 32
Row 385: Null values in columns - Unnamed: 32
Row 386: Null values in columns - Unnamed: 32
Row 387: Null values in columns - Unnamed: 32
Row 388: Null values in columns - Unnamed: 32
Row 389: Null values in columns - Unnamed: 32
Row 390: Null values in columns - Unnamed: 32
Row 391: Null values in columns - Unnamed: 32
Row 392: Null values in columns - Unnamed: 32
Row 393: Null values in columns - Unnamed: 32
Row 394: Null values in columns - Unnamed: 32
Row 395: Null values in columns - Unnamed: 32
Row 396: Null values in columns - Unnamed: 32
Row 397: Null values in columns - Unnamed: 32
Row 398: Null values in columns - Unnamed: 32
Row 399: Null values in columns - Unnamed: 32
Row 400: Null values in columns - Unnamed: 32
Row 401: Null values in columns - Unnamed: 32
Row 402: Null values in columns - Unnamed: 32
Row 403: Null values in columns - Unnamed: 32
Row 404: Null values in columns - Unnamed: 32
Row 405: Null values in columns - Unnamed: 32
Row 406: Null values in columns - Unnamed: 32
Row 407: Null values in columns - Unnamed: 32
Row 408: Null values in columns - Unnamed: 32
Row 409: Null values in columns - Unnamed: 32
Row 410: Null values in columns - Unnamed: 32
Row 411: Null values in columns - Unnamed: 32
Row 412: Null values in columns - Unnamed: 32
Row 413: Null values in columns - Unnamed: 32
Row 414: Null values in columns - Unnamed: 32
Row 415: Null values in columns - Unnamed: 32
Row 416: Null values in columns - Unnamed: 32
Row 417: Null values in columns - Unnamed: 32
Row 418: Null values in columns - Unnamed: 32
Row 419: Null values in columns - Unnamed: 32
Row 420: Null values in columns - Unnamed: 32
Row 421: Null values in columns - Unnamed: 32
Row 422: Null values in columns - Unnamed: 32
Row 423: Null values in columns - Unnamed: 32
Row 424: Null values in columns - Unnamed: 32
Row 425: Null values in columns - Unnamed: 32
Row 426: Null values in columns - Unnamed: 32
Row 427: Null values in columns - Unnamed: 32
Row 428: Null values in columns - Unnamed: 32
Row 429: Null values in columns - Unnamed: 32
Row 430: Null values in columns - Unnamed: 32
Row 431: Null values in columns - Unnamed: 32
Row 432: Null values in columns - Unnamed: 32
Row 433: Null values in columns - Unnamed: 32
Row 434: Null values in columns - Unnamed: 32
Row 435: Null values in columns - Unnamed: 32
Row 436: Null values in columns - Unnamed: 32

In [8]:


# Assuming 'data' is your DataFrame
num_rows, num_columns = df.shape

print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

Number of rows: 569
Number of columns: 33

In [9]:


# Assuming 'data' is your DataFrame
column_number_to_drop = 32 # Replace with the actual column number you want to drop

# Get the column name by column number
column_name_to_drop = df.columns[column_number_to_drop]

# Drop the column by name
df.drop(column_name_to_drop, axis=1, inplace=True)

In [10]:


# Assuming 'data' is your DataFrame
num_rows, num_columns = df.shape

print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

Number of rows: 569
Number of columns: 32

In [11]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [12]:
missing_values_per_row = df.isnull().sum(axis=1)
print(missing_values_per_row)

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    0
Length: 569, dtype: int64

In [13]:


# Specify the row numbers (index) of the first and last columns you want to include
first_column_index = 2  # Replace with the actual index of the first column
last_column_index = 32  # Replace with the actual index of the last column

# Extract feature columns using iloc
x = df.iloc[:, first_column_index:last_column_index + 1]

# Assuming 'target_column' is the target variable
target_column = 'diagnosis'

# Extract the target variable
y = df[target_column]

y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [14]:

from sklearn.model_selection import train_test_split

# Specify the test size (e.g., 0.2 for 80% train, 20% test)
test_size = 0.2

# Use train_test_split to split the data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=test_size, random_state=42)

# Display the shapes of the resulting sets
print("X_train shape:", x_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", x_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (455, 30)
y_train shape: (455,)
X_test shape: (114, 30)
y_test shape: (114,)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Assuming X_train and X_test are your feature sets
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Adjusting the Logistic Regression model
model = LogisticRegression(max_iter=1000, solver='lbfgs')
model.fit(x_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [17]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
y_pred = model.predict(x_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9736842105263158
Classification Report:
               precision    recall  f1-score   support

           B       0.97      0.99      0.98        71
           M       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

Confusion Matrix:
 [[70  1]
 [ 2 41]]